[package]
name = "GoodSignal"
version = "0.2.1"
license = "MIT"
authors = [ "Mark Langen <stravant@gmail.com>" ]
content_root = "src"
files = [ "src/**", "default.project.json" ]

[dependencies]
# None :)
